project:
  type: website
  output-dir: "docs"

website:
  title: "Ian Zablon Owuor"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd
      - text: "CV"
        file: CV.qmd
      - text: "Certificates"
        file: certificates.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/mtunuksi
      - icon: twitter
        href: https://x.com/mtunuksi
format:
  html:
    theme: yaml-gray-theme
    css: styles.css

editor: visual

